# Minimal SLiMS 9 FrankenPHP configuration
# muzub - Full stack developer expert in building AI apps
version: '3'

services:
  app:
    image: dunglas/frankenphp:latest
    ports:
      - "8080:80"
    volumes:
      - ./slims:/app
    depends_on:
      - db
    environment:
      - PHP_INI_MEMORY_LIMIT=256M
      - PHP_INI_UPLOAD_MAX_FILESIZE=50M

  db:
    image: mariadb:10.11
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: slims
      MYSQL_USER: slims
      MYSQL_PASSWORD: slims
    volumes:
      - ./db:/var/lib/mysql
